title: Dr. XU, Hui 徐輝
logo: profile.png
description: 副教授（博士生导师）<br> 复旦大学 计算与智能创新学院  <br> 地址：上海市 杨浦区 淞沪路2005号 <br> 复旦大学江湾校区 交叉二号楼D6023室 
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
